### ISSUE TITLE
Progress screen doesn't appear in the task bar

### ISSUE THREAD

**Issue by es20490446e** [openSUSE/imagewriter#21]
HOW TO REPRODUCE:
1. Write an image to an USB drive.
2. When the progress bar appears, open the file manager full screen, for example.
3. Try switching to the progress bar window using the icons in the task bar.

RESULT:
There's no method for switching to the progress screen, other than minimising all the forefront windows.

**Comment by momozor** [comment]
Hi. Is this still happening? I can't reproduce this. I did all the steps, and the progress screen will be always on top if I click it from the task bar, regardless if I opened a file manager fullscreen and left it there.

**Comment by uciharis** [comment]
hi, i was also faced this issue. i couldnt see any progress bar, but i knew there is progress bar menu that floated on home ( and a notif as ' writing' )

here the screenshot i got :
![Screenshot from 2024-05-12 22-46-55](https://github.com/openSUSE/imagewriter/assets/40335023/ee245451-1ead-46e6-96ee-650b7b31bea0)


you can have an access to hidden progress bar by press 'windows' button

**Comment by es20490446e** [comment]
I would open a new issue.
